<?xml version="1.0"?>
<package format="2">
  <name>mm_run</name>
  <version>0.0.0</version>
  <description>Mobile manipulation run/launch package</description>

  <maintainer email="todo@todo.todo">Maintainer</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <depend>mm_simulator</depend>
  <depend>mm_control</depend>
  <depend>mm_plan</depend>
  <depend>mm_utils</depend>

  <export>
  </export>
</package>
